{
 "title": "Medical Monitoring",
 "description": "Dashboard for checking patient status",
 "time": { "from": "2024-05-31T12:55:00.000Z", "to": "2024-05-31T13:18:05.000Z" },
 "panels": [
  {
   "title": "Average Fasting Blood Sugar",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT AVG(fbs) FROM MedicalMonitoring.BodyData LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Thalach",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Frequency" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT AVG(thalach) FROM MedicalMonitoring.BodyData LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Trestbps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT AVG(trestbps) FROM MedicalMonitoring.BodyData LIMIT 50 "
    }
   ]
  },
  {
   "title": "Real Time - Angular Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Radiants*sec^2" } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT last_ang_acc AS \"value\", timestamp AS \"time\" FROM MedicalMonitoring.MovementData LIMIT 50"
    }
   ]
  },
  {
   "title": "Real Time - Linear Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT lastlin_acc, timestamp FROM MedicalMonitoring.MovementData "
    }
   ]
  },
  {
   "title": "Real Time - Thalach",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Frequency" } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT thalach AS \"value\", timestamp AS \"time\" FROM MedicalMonitoring.BodyData LIMIT 50"
    }
   ]
  },
  {
   "title": "Real Time - Trestbps",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "dataset": "MedicalMonitoring",
     "rawSql": "SELECT trestbps AS \"value\", timestamp AS \"time\" FROM MedicalMonitoring.BodyData LIMIT 50"
    }
   ]
  }
 ]
}